# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import OrderServiceProto2_pb2 as OrderServiceProto2__pb2


class OrderService2Stub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getOrderDetail = channel.unary_unary(
                '/grpcnative.OrderService2/getOrderDetail',
                request_serializer=OrderServiceProto2__pb2.OrderRequest2.SerializeToString,
                response_deserializer=OrderServiceProto2__pb2.OrderDetail2.FromString,
                )


class OrderService2Servicer(object):
    """The greeting service definition.
    """

    def getOrderDetail(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderService2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getOrderDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.getOrderDetail,
                    request_deserializer=OrderServiceProto2__pb2.OrderRequest2.FromString,
                    response_serializer=OrderServiceProto2__pb2.OrderDetail2.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcnative.OrderService2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderService2(object):
    """The greeting service definition.
    """

    @staticmethod
    def getOrderDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcnative.OrderService2/getOrderDetail',
            OrderServiceProto2__pb2.OrderRequest2.SerializeToString,
            OrderServiceProto2__pb2.OrderDetail2.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
