# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import OrderServiceProto1_pb2 as OrderServiceProto1__pb2


class OrderService1Stub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getOrderDetail = channel.unary_unary(
                '/grpcnative.OrderService1/getOrderDetail',
                request_serializer=OrderServiceProto1__pb2.OrderRequest1.SerializeToString,
                response_deserializer=OrderServiceProto1__pb2.OrderDetail1.FromString,
                )


class OrderService1Servicer(object):
    """The greeting service definition.
    """

    def getOrderDetail(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderService1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getOrderDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.getOrderDetail,
                    request_deserializer=OrderServiceProto1__pb2.OrderRequest1.FromString,
                    response_serializer=OrderServiceProto1__pb2.OrderDetail1.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcnative.OrderService1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderService1(object):
    """The greeting service definition.
    """

    @staticmethod
    def getOrderDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcnative.OrderService1/getOrderDetail',
            OrderServiceProto1__pb2.OrderRequest1.SerializeToString,
            OrderServiceProto1__pb2.OrderDetail1.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
