# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrderServiceProto2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrderServiceProto2.proto',
  package='grpcnative',
  syntax='proto3',
  serialized_options=b'\n\014sb.rpc.grpc2B\022OrderServiceProto2P\001',
  serialized_pb=b'\n\x18OrderServiceProto2.proto\x12\ngrpcnative\" \n\rOrderRequest2\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"X\n\x0cOrderDetail2\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\x04\x12\r\n\x05price\x18\x03 \x01(\x01\x12\r\n\x05\x62uyer\x18\x04 \x01(\t\x12\x0e\n\x06seller\x18\x05 \x01(\t2X\n\rOrderService2\x12G\n\x0egetOrderDetail\x12\x19.grpcnative.OrderRequest2\x1a\x18.grpcnative.OrderDetail2\"\x00\x42$\n\x0csb.rpc.grpc2B\x12OrderServiceProto2P\x01\x62\x06proto3'
)




_ORDERREQUEST2 = _descriptor.Descriptor(
  name='OrderRequest2',
  full_name='grpcnative.OrderRequest2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderId', full_name='grpcnative.OrderRequest2.orderId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=72,
)


_ORDERDETAIL2 = _descriptor.Descriptor(
  name='OrderDetail2',
  full_name='grpcnative.OrderDetail2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpcnative.OrderDetail2.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='grpcnative.OrderDetail2.date', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='grpcnative.OrderDetail2.price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buyer', full_name='grpcnative.OrderDetail2.buyer', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seller', full_name='grpcnative.OrderDetail2.seller', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['OrderRequest2'] = _ORDERREQUEST2
DESCRIPTOR.message_types_by_name['OrderDetail2'] = _ORDERDETAIL2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderRequest2 = _reflection.GeneratedProtocolMessageType('OrderRequest2', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREQUEST2,
  '__module__' : 'OrderServiceProto2_pb2'
  # @@protoc_insertion_point(class_scope:grpcnative.OrderRequest2)
  })
_sym_db.RegisterMessage(OrderRequest2)

OrderDetail2 = _reflection.GeneratedProtocolMessageType('OrderDetail2', (_message.Message,), {
  'DESCRIPTOR' : _ORDERDETAIL2,
  '__module__' : 'OrderServiceProto2_pb2'
  # @@protoc_insertion_point(class_scope:grpcnative.OrderDetail2)
  })
_sym_db.RegisterMessage(OrderDetail2)


DESCRIPTOR._options = None

_ORDERSERVICE2 = _descriptor.ServiceDescriptor(
  name='OrderService2',
  full_name='grpcnative.OrderService2',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=164,
  serialized_end=252,
  methods=[
  _descriptor.MethodDescriptor(
    name='getOrderDetail',
    full_name='grpcnative.OrderService2.getOrderDetail',
    index=0,
    containing_service=None,
    input_type=_ORDERREQUEST2,
    output_type=_ORDERDETAIL2,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERSERVICE2)

DESCRIPTOR.services_by_name['OrderService2'] = _ORDERSERVICE2

# @@protoc_insertion_point(module_scope)
